---
title: 'RMarkdown:  In Class Assignment'
author: "Kevin Sheard"
date: "Data 2401"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) ## this line makes all the code show! 
  ## and these lines are comments - anything behind a '#' doesn't run!
```


Reminder: There is a "Markdown Help" page available in RStudio. 


# Your Work Here

## Wise words

From Shakespeare:

> Be not afraid of greatness. Some are born great, some achieve greatness, and others have greatness thrust upon them.

Here is a [link](https://writingexplained.org/idiom-dictionary/some-people-are-born-great) for more information on that quote

## My semester

Course Number | Course Title | Instructor Name
 ------------ | ------------ | -------------- 
 __ART_1302__ | _History of Art: Renaissance to Present_ | Jessica Kubala 
 __CS_1311__ | _Introduction to CS with Python_ |  Joseph Kamto
 __Data_2401__ | _Data Science 1_ | Katherine Shoemaker
 __Math_2305__ | _Discrete Math_ | Mitsue Nakamura
 __Math_3302__ | _Probability and Statistics_ | Plamen Simeonov
 
 
## I Recommend Kanye West

```
I'm living in that 21st century
Doing something mean to it
Do it better than anybody you ever seen do it
Screams from the haters, got a nice ring to it
I guess every superhero need his theme music

No one man should have all that power
The clock's ticking, I just count the hours
Stop tripping, I'm tripping off the power
(21st-century schizoid man)

The system broken, and the school's closed, the prisons open
We ain't got nothin' to lose, ma'fucka, we rollin'
Huh? Ma'fucka, we rollin'
With some light-skinned girls and some Kelly Rowlands
In this white man's world, we the ones chosen
So goodnight, cruel world, I'll see you in the mornin'
Huh? I'll see you in the mornin'
This is way too much, I need a moment

No one man should have all that power
The clock's ticking, I just count the hours
Stop tripping, I'm tripping off the power
'Til then, fuck that, the world's ours

And they say, and they say
And they say, and they say
And they say, and they say
(21st-century schizoid man)

Fuck SNL and the whole cast
Tell 'em Yeezy said they can kiss my whole ass
More specifically, they can kiss my asshole
I'm an asshole? You niggas got jokes
You short-minded niggas thoughts is Napoleon
My furs is Mongolian, my ice brought the goalies in
Now I embody every characteristic of the egotistic
He knows he so fuckin' gifted
I just needed time alone, with my own thoughts
Got treasures in my mind but couldn't open up my own vault
My childlike creativity, purity and honesty
Is honestly being crowded by these grown thoughts
Reality is catching up with me
Taking my inner child, I'm fighting for custody
With these responsibilities that they entrusted me
As I look down at my diamond encrusted piece

Thinkin', no one man should have all that power
The clock's ticking, I just count the hours
Stop tripping, I'm tripping off the powder
'Til then, fuck that, the world's ours

And they say, and they say
And they say, and they say
And they say, and they say
(21st-century schizoid man)

Colin Powells, Austin Powers
Lost in translation with a whole fuckin' nation
They say I was the abomination of Obama's nation
Well that's a pretty bad way to start the conversation
At the end of the day, goddammit, I'm killin' this shit
I know damn well y'all feeling this shit
I don't need your pussy, bitch, I'm on my own dick
I ain't gotta power trip, who you goin' home with?
How 'Ye doing? I'm surviving
I was drinking earlier, now I'm driving
Where the bad bitches, huh? Where y'all hiding?
I got the power make your life so exciting

Now this will be a beautiful death
I'm jumping out the window
I'm letting everything go
I'm letting everything go
Mmm, now this will be a beautiful death
I'm jumping out the window
I'm letting everything go
I'm letting everything go
Now this will be a beautiful death
Jumping out the window
Letting everything go
Letting everything go
You got the power to let power go?
(21st-century schizoid man)

```

### Albums by Kanye West

* The College Dropout
* Late Registration
* Graduation
* 808s and Heartbreak
* My Beautiful Dark Twisted Fantasy
* Yeezus
* The Life of Pablo
* Jesus is King
* Ye
* Donda
* Donda 2

 
Below the "Your work here" section header, do the following 3 things. To turn this in, knit the RMarkdown file, and zip and submit the html.  

1. Make a subsection called "Wise words". Put your favorite quote in a block quote. Add a functioning link to a website that provides more information about that quote.

2. Make a subsection called "My semester". Make a three column table of the current courses you are taking, with separate columns for course number (put those in __bold__), course title (put those in _italics_), and instructor name.

3. Lastly, make subsection called "I recommend", and add some information about your favorite author or musician.

+ A _subsubheading_ with the name of the artist or author;    
+ An example of their writing or lyrics (formatted in a *plain code block*);   
+ A _list_ of things they have written or performed (remember to use the formatting markup for a list!).     


Note that you can click "Knit" as you go along to see what the final results are going to look like. **Once you're done, commit the changes and push the repo back to your assignment on GitHub!**
 
